language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: g++-5
      env: COMPILER=g++ -std=c++11

script:
  - chmod 777 ./cpplint.py
  - ./cpplint.py ./hello_world.cpp
  - mkdir build && cd build
  - cmake .. && make
#  - ./executable
