language: cpp

notifications:
  email: false

matrix:
  include:
    - os: osx
      compiler: g++-5
      env: COMPILER=g++ -std=c++11

script:
  - mkdir build && cd build
  - cmake .. && make
  - ./executable
